version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8132:8132"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
  postgres:
    image: postgres

    restart: always
    environment:
      POSTGRESQL_ROOT_PASSWORD: bank_pwd
      POSTGRESQL_DATABASE: bank_db
